project_id = "fhbxujfihslmcbqxolyb"

[functions.analyze-meeting]
verify_jwt = false

[functions.research]
verify_jwt = false

[functions.transcribe]
verify_jwt = false

[functions.project-readme-get]
verify_jwt = true

[functions.project-readme-post]
verify_jwt = true
